name: qrcode_keeper
description: This application makes it easy to keep track of your QR codes while marking them as used or outdated.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  qr_flutter: ^4.0.0
  mobile_scanner: ^2.0.0
  sqflite: ^2.1.0
  intl: ^0.17.0
  # month_year_picker: ^0.2.0+2
  month_year_picker:
    git:
      url: https://github.com/LamsaLL/month-year-picker.git
      ref: fix-months-overflow
  persistent_bottom_nav_bar: ^5.0.2
  flutter_local_notifications: ^12.0.2
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true