name: Build & Release

on: 
  push: # after successfully merged pull request the push is executed.
    branches:
      - "staging"
      - "production"

jobs:
  set_variable:
    name: Workaround for passing env vars as inputs
    runs-on: ubuntu-latest
    outputs:
      flavor_out: ${{ steps.set_variables_step.outputs.flavor_out }}
    steps:
      - name: Print inputs passed to the call-build-workflow
        id: set_variables_step
        run: |
          echo "flavor: $GITHUB_REF_NAME"
          echo "::set-output name=flavor_out::$GITHUB_REF_NAME"

  call-build-workflow:
    needs: 
      - set_variable
    name: "Calling Build & Release reusable workflow"
    uses: ./.github/workflows/build_release_reusable.yml
    with:
      flavor: ${{ needs.set_variable.outputs.flavor_out }}
      tag-suffix: -stag
    secrets: inherit
      