on: 
  pull_request:
    branches:
      - staging

  push:
    branches:
      - staging

name: Build & Release
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.3'
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk --split-per-abi "--release" --flavor staging -t "lib/main_stag.dart"
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/staging/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}