name: Build & Release

on: 
  push: # after successfully merged pull request the push is executed.
    branches:
      - staging
      - production

jobs:
  call-build-workflow:
    name: "Calling Build & Release reusable workflow"
    uses: ./.github/workflows/build_release_reusable.yml
    with:
      flavor: "$GITHUB_REF_NAME"
      tag-suffix: -stag
    secrets:
      token: ${{ secrets.TOKEN }}